export default {
  zoomercontainer: {
    position: 'relative',
    width: '100%',
    height: 'auto',
    backgroundSize: 'contain',
    backgroundRepeat: 'no-repeat',
    backgroundPosition: 'center center',
  },
  zoomer: {
    position: 'absolute',
    top: '-75px',
    left: '-75px',
    width: '150px',
    height: '150px',
    background: 'white',
    overflow: 'hidden',
    border: '1px solid',
    borderRadius: '50%',
    pointerEvents: 'none',
  },
  zoomercontainer__inner__image: {
    position: 'absolute',
    top: '50%',
    left: '50%',
    backgroundSize: 'contain',
    backgroundRepeat: 'no-repeat',
    backgroundPosition: 'center center',
    transformOrigin: ' top left',
    pointerEvents: 'none',
  },
};
